In [1]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import plotly.graph_objects as go
import seaborn as sns
import pybedtools
from scipy.stats import norm
import seaborn as sns
pybedtools.helpers.set_tempdir('/data/projects/temp')

In [2]:
attention_score_path = "/data/projects/Enhancer/DNABERT_Output/Visualization_Enhancer_Encode/Predictions/atten_score200.npy"
prediction_path = "/data/projects/Enhancer/DNABERT_Output/Visualization_Enhancer_Encode/Predictions/pred_results.npy"
#data_path = "/data/projects/Enhancer/Finetuned_data/Consensus_filter_1/Visualization/dev.tsv"
raw_data_path = "/data/projects/Enhancer/Finetuned_data/Consensus_filter_1/RF_dev.tsv"
bed_folder_path= "/data/projects/Resources/ENCODE_data/ChIP-seq_data/ChIP-seq_peaks_bed"
# chi_seq_path= "/data/projects/Enhancer/ChipSeq_Intersection/ChIP-seq_peaks.csv"

In [3]:
attention_data = np.load(attention_score_path)
pred_result = np.load(prediction_path)
# #data = pd.read_csv(data_path, sep="\t") 
raw_data = pd.read_csv(raw_data_path, sep="\t")
#intersected_chip_data = pd.read_csv(chi_seq_path, sep=",")

In [4]:
pred_result

array([0.80196536, 0.00386043, 0.1981992 , ..., 0.21390572, 0.39133212,
       0.8598932 ], dtype=float32)

In [5]:
attention_data

array([[0.15736438, 0.12613323, 0.12205527, ..., 0.08286749, 0.09156235,
        0.1009498 ],
       [0.0706074 , 0.06797632, 0.07054477, ..., 0.04955077, 0.04924984,
        0.05282408],
       [0.12788138, 0.13338041, 0.12745156, ..., 0.05847935, 0.06300342,
        0.08041372],
       ...,
       [0.13845803, 0.12782378, 0.12814937, ..., 0.08183175, 0.08405915,
        0.07355097],
       [0.06446469, 0.09207337, 0.08236827, ..., 0.0796929 , 0.08804073,
        0.11264496],
       [0.0781696 , 0.08220336, 0.08146374, ..., 0.06815664, 0.07253033,
        0.09001699]])

In [6]:
true_data = raw_data[['coord',"sequence","label"]]
true_data

,coord,sequence,label
0,chr13:23652031-23652230,TCCTTTCTGCACAGGGTTATTACAGCGCCCAGAAAGTGGGTATGTA...,1
1,chr14:17061576-17061775,TCAAATAAAAACTAGACAGAAGCATTCTCATAAGCTTGTTTGTGAT...,0
2,chr9:24999931-25000130,CCACCAAGGAGACCTCATTTGTAGATTTGGCAAAGTATGGCACAAT...,0
3,chr18:52169445-52169644,CATTTAAATTTTAAATGTATTTAACATTTAGAGAATAGTATAAATA...,0
4,chr9:32366053-32366252,AAGTTGAAATTAAATAAATCCTAAATTTGAATCAGGTGTGTTGGTA...,0
...,...,...,...
3186,chr9:38725772-38725971,CCCACCACCACGCCTGGCTAATTTTTCTGTATTTTCAGTAGAGATG...,1
3187,chr1:105315643-105315842,TATTTTATTTTTACTGTTTTGTCCCACATGAGCTTGCTTATATATT...,0
3188,chr7:27950006-27950205,GAGATAACTTACCTGCTTTTCACGATACTTTTGATACAATCTCATT...,1
3189,chr2:171047833-171048032,TCATCTTCTAACCACTCTGGATTATATCACCAATTATAAACGGCTT...,1
3190,chr15:41720338-41720537,CCTGCCTGAGCAACATAGCAATACTTCCATCTCTACTAAAAATAAA...,1

In [7]:
categorical_predictions = (pred_result > 0.5).astype(int)
true_data['Prediction_result'] = categorical_predictions 
df_visualize = true_data[(true_data['label'] == 1) & (true_data['Prediction_result'] == 1)]
# df_visualize_all = df_visualize.merge(true_data, left_index=True, right_index=True, how='inner')
df_visualize

/data/projects/temp/ipykernel_824897/568859000.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  true_data['Prediction_result'] = categorical_predictions

,coord,sequence,label,Prediction_result
0,chr13:23652031-23652230,TCCTTTCTGCACAGGGTTATTACAGCGCCCAGAAAGTGGGTATGTA...,1,1
11,chr10:45519836-45520035,GAGGTGGAATCAGTAAAACTTATTGATGAGTGGCGCATTAAGAGCA...,1,1
12,chr3:193057772-193057971,TAGGTTTTACAATTCCTTTCAACACCAAATTAAGATCAGAAGGTAT...,1,1
13,chr3:77507468-77507667,TCTTGCACACAGAAGACTGCAAGAATGGGCTCTGCCTATCTAAAAA...,1,1
18,chr1:187980069-187980268,GCACTGTGGCTCATGCCTGTAATCCCAGCACTTTGGGAGGCTGAGG...,1,1
...,...,...,...,...
3181,chr5:64261727-64261926,ATATCAGGTGGAAAGAAACAAAGCTGCTCAAGTGAGAACAACCAAA...,1,1
3183,chr12:43813667-43813866,TCTACACTCTCAAAGAAGCTCATTTCAAGGCCCTTCCTTACTCAGT...,1,1
3184,chr1:204552002-204552201,GTGGACCGGGCGTAGTGGCTCACGCCTGTAATCCCAACACTTTGGG...,1,1
3186,chr9:38725772-38725971,CCCACCACCACGCCTGGCTAATTTTTCTGTATTTTCAGTAGAGATG...,1,1
3190,chr15:41720338-41720537,CCTGCCTGAGCAACATAGCAATACTTCCATCTCTACTAAAAATAAA...,1,1

In [8]:
positive_attention_score = attention_data[df_visualize.index.values]
positive_attention_score

array([[0.15736438, 0.12613323, 0.12205527, ..., 0.08286749, 0.09156235,
        0.1009498 ],
       [0.14155952, 0.11704731, 0.10161122, ..., 0.08688743, 0.08341995,
        0.08914666],
       [0.1592955 , 0.13399013, 0.1245085 , ..., 0.06538571, 0.06437823,
        0.0754427 ],
       ...,
       [0.09295924, 0.08530137, 0.08252531, ..., 0.05208671, 0.04840521,
        0.05569853],
       [0.08796743, 0.09712145, 0.10442137, ..., 0.0893162 , 0.10288811,
        0.11376228],
       [0.0781696 , 0.08220336, 0.08146374, ..., 0.06815664, 0.07253033,
        0.09001699]])

In [65]:
attention_cutoff_path = os.path.dirname(attention_score_path)+"/Visualization/Attention_Cutoff/CDF"
if not os.path.exists(attention_cutoff_path):
    os.makedirs(attention_cutoff_path)

In [64]:
def find_subsequent_regions_above_percentile(arr, percentile_val, min_length=3):
    # Calculate the desired percentile for each row
    row_percentiles = np.percentile(arr, percentile_val, axis=1)
    regions = []

    for i, row in enumerate(arr):
        cutoff = row_percentiles[i]
        title = df_visualize['coord'].iloc[i]
        #print(title)
        start, end = map(int, title.split(":")[1].split("-"))
        chr_name = title.split(":")[0]
        # Find indices where values are >= cutoff
        above_cutoff_indices = np.where(row >= cutoff)[0]
        #print(above_cutoff_indices)
        
        # Find subsequent regions of indices
        if len(above_cutoff_indices) > 0:
            start_idx = above_cutoff_indices[0]
            end_idx = start_idx
            
            current_regions = []
            
            for idx in above_cutoff_indices[1:]:
                if idx == end_idx + 1:  # Check if this index is subsequent
                    end_idx = idx
                else:
                    if (end_idx - start_idx + 1) >= min_length:
                        current_regions.append((chr_name , start + start_idx, start+ end_idx, title))
                    start_idx = idx
                    end_idx = idx
            
            if (end_idx - start_idx + 1) >= min_length:
                current_regions.append((chr_name , start+ start_idx, start+ end_idx, title))
            regions.extend(current_regions)
        else:
            print("Check the region ", title)
        #print(regions)
        #input()
    # Convert to DataFrame
    df_result = pd.DataFrame(regions, columns=['chr_name', 'attention_start', 'attention_end', 'coord'])
    
    return df_result

In [66]:
for cut_off_value in [70, 75, 80, 85, 90, 95]:
    cut_off_bed_file = find_subsequent_regions_above_percentile(positive_attention_score, cut_off_value)
    cut_off_bed_file.to_csv(attention_cutoff_path+"/attention_BED_cutoff_{}.tsv".format(cut_off_value) , sep="\t", index=False)

In [59]:
cut_off_bed_file

     chr_name  attention_start  attention_end                     coord
0       chr13         23652031       23652043   chr13:23652031-23652230
1       chr13         23652161       23652164   chr13:23652031-23652230
2       chr10         45519836       45519839   chr10:45519836-45520035
3       chr10         45519860       45519863   chr10:45519836-45520035
4       chr10         45519989       45519996   chr10:45519836-45520035
...       ...              ...            ...                       ...
3226     chr1        204552009      204552024  chr1:204552002-204552201
3227     chr9         38725774       38725786    chr9:38725772-38725971
3228     chr9         38725901       38725904    chr9:38725772-38725971
3229    chr15         41720396       41720407   chr15:41720338-41720537
3230    chr15         41720425       41720428   chr15:41720338-41720537

[3231 rows x 4 columns]