In [243]:
import os
import numpy as np
import pandas as pd
import sklearn
from io import StringIO
from IPython.display import display
import scipy.stats as stats

In [1]:
data_path = "/data/private/pdutta/Collab_data/David_data/GSE78220_PatientFPKM.xlsx"

In [172]:
df  = pd.read_excel(data_path)
df = df.set_index('Gene')
df.index.name = None

/home/campus.stonybrook.edu/pdutta/anaconda3/envs/rapid_sampling/lib/python3.9/site-packages/openpyxl/worksheet/_read_only.py:79: UserWarning: Unknown extension is not supported and will be removed
  for idx, row in parser.parse():

In [173]:
df

,Pt1.baseline,Pt2.baseline,Pt4.baseline,Pt5.baseline,Pt6.baseline,Pt7.baseline,Pt8.baseline,Pt9.baseline,Pt10.baseline,Pt12.baseline,...,Pt25.baseline,Pt27A.baseline,Pt27B.baseline,Pt28.baseline,Pt29.baseline,Pt31.baseline,Pt32.baseline,Pt35.baseline,Pt37.baseline,Pt38.baseline
A1BG,8.025380,317.594000,5.747295,6.859570,1.563465,21.565850,11.370550,8.156810,4.346750,6.508715,...,40.408950,6.093810,7.191755,8.595985,5.460340,14.788600,17.377200,11.644200,15.000300,4.475170
A1BG-AS1,0.677503,28.378200,0.471394,0.347623,0.201760,8.926245,3.853125,2.539610,1.914350,4.797930,...,0.441924,0.265769,0.513015,1.314753,3.155180,0.254531,0.673230,0.718414,0.388571,0.253978
A1CF,0.000000,18.109400,0.000000,0.000000,0.011276,0.000000,0.003263,0.001398,0.000000,0.000000,...,0.000000,0.000000,0.001768,0.188226,0.009519,0.000000,0.000000,0.000000,0.000000,0.000000
A2M,185.304000,455.160000,81.008200,41.410650,136.163500,44.669350,119.017500,232.675000,501.697000,530.237500,...,300.813000,390.299500,364.513500,67.114500,557.991500,50.436000,121.544000,55.713900,39.667300,495.157000
A2M-AS1,0.363531,2.864455,0.201285,0.040821,0.417423,1.039475,3.126025,4.216800,1.489845,1.868520,...,2.511090,0.397716,0.284776,0.627700,1.295220,0.129179,0.824253,0.172745,1.587210,1.049580
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ZYG11A,0.007498,0.054845,0.000000,0.000000,0.000000,2.066555,0.000000,0.006864,0.022734,0.010006,...,0.018591,0.003724,0.004214,0.062258,0.091105,0.044149,0.062350,0.044827,0.019972,0.127983
ZYG11B,7.302015,5.610695,4.003770,5.655590,5.824330,4.543575,3.886960,4.239625,5.457640,3.121325,...,3.069715,6.476460,9.289845,2.627145,5.611555,2.126950,7.240730,7.467930,3.819750,4.669140
ZYX,61.044750,37.386500,54.046500,48.225750,69.135100,26.519050,177.418000,72.373000,71.654150,379.135000,...,68.012400,75.030500,46.602200,73.060750,52.785900,237.497000,76.482300,60.530900,70.407400,117.978000
ZZEF1,3.463620,3.190875,4.797630,4.612085,6.704615,3.711905,5.336710,4.941620,3.896335,3.783140,...,3.566765,4.318730,4.776135,6.372490,5.554160,2.759710,3.578340,5.431990,2.591630,7.151890
ZZZ3,14.703500,9.412335,6.409365,9.785310,9.316395,6.672100,8.664665,6.003945,7.293775,11.620600,...,5.707475,12.048000,16.138450,5.963820,7.878390,1.294190,4.694090,10.149300,5.699450,6.480940

In [174]:
temp_df = df.loc[['PHGDH','SFXN1','SLC1A5']]
temp_df

,Pt1.baseline,Pt2.baseline,Pt4.baseline,Pt5.baseline,Pt6.baseline,Pt7.baseline,Pt8.baseline,Pt9.baseline,Pt10.baseline,Pt12.baseline,...,Pt25.baseline,Pt27A.baseline,Pt27B.baseline,Pt28.baseline,Pt29.baseline,Pt31.baseline,Pt32.baseline,Pt35.baseline,Pt37.baseline,Pt38.baseline
PHGDH,178.13350,12.83100,125.110000,161.8785,50.40410,103.41350,69.38070,38.1661,14.88905,51.40225,...,2.066750,293.837000,301.22950,53.68660,22.73570,22.1335,50.75010,130.9870,7.05431,20.1907
SFXN1,20.14255,26.15465,7.824695,20.8851,14.31120,8.21688,17.22985,17.7206,18.93855,9.77528,...,7.371015,2.033025,1.31603,12.35185,10.05128,18.8179,7.06392,16.6373,5.14168,15.0603
SLC1A5,53.88820,10.17109,10.613000,53.9192,10.07938,831.76650,69.47360,61.1779,77.93055,64.15265,...,120.689000,52.617150,39.34665,84.07135,97.20070,140.0520,82.62550,99.3535,42.87030,56.5993

In [175]:
df_transposed = temp_df.T
df_transposed['mean'] = df_transposed.mean(axis=1)
df_transposed

                    PHGDH      SFXN1     SLC1A5        mean
Pt1.baseline    178.13350  20.142550   53.88820   84.054750
Pt2.baseline     12.83100  26.154650   10.17109   16.385580
Pt4.baseline    125.11000   7.824695   10.61300   47.849232
Pt5.baseline    161.87850  20.885100   53.91920   78.894267
Pt6.baseline     50.40410  14.311200   10.07938   24.931560
Pt7.baseline    103.41350   8.216880  831.76650  314.465627
Pt8.baseline     69.38070  17.229850   69.47360   52.028050
Pt9.baseline     38.16610  17.720600   61.17790   39.021533
Pt10.baseline    14.88905  18.938550   77.93055   37.252717
Pt12.baseline    51.40225   9.775280   64.15265   41.776727
Pt13.baseline    13.29660   9.770205   24.62405   15.896952
Pt14.baseline    21.93350  17.308900  117.14900   52.130467
Pt15.baseline    32.30460  15.100100   95.36450   47.589733
Pt16.OnTx       171.08400  15.790700  127.37900  104.751233
Pt19.baseline   233.08650   5.727675  431.20100  223.338392
Pt20.baseline    54.03325   7.417420   60.76985   40.740173
Pt22.baseline    16.36940  10.583950   37.02740   21.326917
Pt23.baseline    63.51005  14.784500  117.85450   65.383017
Pt25.baseline     2.06675   7.371015  120.68900   43.375588
Pt27A.baseline  293.83700   2.033025   52.61715  116.162392
Pt27B.baseline  301.22950   1.316030   39.34665  113.964060
Pt28.baseline    53.68660  12.351850   84.07135   50.036600
Pt29.baseline    22.73570  10.051280   97.20070   43.329227
Pt31.baseline    22.13350  18.817900  140.05200   60.334467
Pt32.baseline    50.75010   7.063920   82.62550   46.813173
Pt35.baseline   130.98700  16.637300   99.35350   82.325933
Pt37.baseline     7.05431   5.141680   42.87030   18.355430
Pt38.baseline    20.19070  15.060300   56.59930   30.616767

In [176]:
df_transposed['z_score'] = (df_transposed['mean']-df_transposed['mean'].mean())/df_transposed['mean'].std()

In [177]:
df_transposed

                    PHGDH      SFXN1     SLC1A5        mean   z_score
Pt1.baseline    178.13350  20.142550   53.88820   84.054750  0.245188
Pt2.baseline     12.83100  26.154650   10.17109   16.385580 -0.809681
Pt4.baseline    125.11000   7.824695   10.61300   47.849232 -0.319206
Pt5.baseline    161.87850  20.885100   53.91920   78.894267  0.164743
Pt6.baseline     50.40410  14.311200   10.07938   24.931560 -0.676461
Pt7.baseline    103.41350   8.216880  831.76650  314.465627  3.836976
Pt8.baseline     69.38070  17.229850   69.47360   52.028050 -0.254064
Pt9.baseline     38.16610  17.720600   61.17790   39.021533 -0.456818
Pt10.baseline    14.88905  18.938550   77.93055   37.252717 -0.484391
Pt12.baseline    51.40225   9.775280   64.15265   41.776727 -0.413868
Pt13.baseline    13.29660   9.770205   24.62405   15.896952 -0.817298
Pt14.baseline    21.93350  17.308900  117.14900   52.130467 -0.252467
Pt15.baseline    32.30460  15.100100   95.36450   47.589733 -0.323251
Pt16.OnTx       171.08400  15.790700  127.37900  104.751233  0.567818
Pt19.baseline   233.08650   5.727675  431.20100  223.338392  2.416428
Pt20.baseline    54.03325   7.417420   60.76985   40.740173 -0.430026
Pt22.baseline    16.36940  10.583950   37.02740   21.326917 -0.732652
Pt23.baseline    63.51005  14.784500  117.85450   65.383017 -0.045878
Pt25.baseline     2.06675   7.371015  120.68900   43.375588 -0.388944
Pt27A.baseline  293.83700   2.033025   52.61715  116.162392  0.745702
Pt27B.baseline  301.22950   1.316030   39.34665  113.964060  0.711433
Pt28.baseline    53.68660  12.351850   84.07135   50.036600 -0.285108
Pt29.baseline    22.73570  10.051280   97.20070   43.329227 -0.389667
Pt31.baseline    22.13350  18.817900  140.05200   60.334467 -0.124578
Pt32.baseline    50.75010   7.063920   82.62550   46.813173 -0.335357
Pt35.baseline   130.98700  16.637300   99.35350   82.325933  0.218238
Pt37.baseline     7.05431   5.141680   42.87030   18.355430 -0.778974
Pt38.baseline    20.19070  15.060300   56.59930   30.616767 -0.587836

In [178]:
df_response = pd.read_csv("/data/private/pdutta/Collab_data/David_data/GSE78220_response.csv", sep=",")

In [179]:
df_response['Patient ID'] = df_response['Patient ID'].astype(str) + '.baseline'
df_response = df_response.set_index('Patient ID')
df_response.index.name = None

In [180]:
df_response.groupby('Response').size()

Response
NR    17
R     22
dtype: int64

In [181]:
df_merge = pd.merge(df_transposed, df_response, left_index=True, right_index=True)
df_merge

                    PHGDH      SFXN1     SLC1A5        mean   z_score Response
Pt1.baseline    178.13350  20.142550   53.88820   84.054750  0.245188       NR
Pt2.baseline     12.83100  26.154650   10.17109   16.385580 -0.809681        R
Pt4.baseline    125.11000   7.824695   10.61300   47.849232 -0.319206        R
Pt5.baseline    161.87850  20.885100   53.91920   78.894267  0.164743        R
Pt6.baseline     50.40410  14.311200   10.07938   24.931560 -0.676461        R
Pt7.baseline    103.41350   8.216880  831.76650  314.465627  3.836976       NR
Pt8.baseline     69.38070  17.229850   69.47360   52.028050 -0.254064        R
Pt9.baseline     38.16610  17.720600   61.17790   39.021533 -0.456818        R
Pt10.baseline    14.88905  18.938550   77.93055   37.252717 -0.484391       NR
Pt12.baseline    51.40225   9.775280   64.15265   41.776727 -0.413868       NR
Pt13.baseline    13.29660   9.770205   24.62405   15.896952 -0.817298        R
Pt14.baseline    21.93350  17.308900  117.14900   52.130467 -0.252467       NR
Pt15.baseline    32.30460  15.100100   95.36450   47.589733 -0.323251        R
Pt19.baseline   233.08650   5.727675  431.20100  223.338392  2.416428        R
Pt20.baseline    54.03325   7.417420   60.76985   40.740173 -0.430026       NR
Pt22.baseline    16.36940  10.583950   37.02740   21.326917 -0.732652       NR
Pt23.baseline    63.51005  14.784500  117.85450   65.383017 -0.045878       NR
Pt25.baseline     2.06675   7.371015  120.68900   43.375588 -0.388944       NR
Pt27A.baseline  293.83700   2.033025   52.61715  116.162392  0.745702        R
Pt27B.baseline  301.22950   1.316030   39.34665  113.964060  0.711433        R
Pt28.baseline    53.68660  12.351850   84.07135   50.036600 -0.285108        R
Pt29.baseline    22.73570  10.051280   97.20070   43.329227 -0.389667       NR
Pt31.baseline    22.13350  18.817900  140.05200   60.334467 -0.124578       NR
Pt32.baseline    50.75010   7.063920   82.62550   46.813173 -0.335357       NR
Pt35.baseline   130.98700  16.637300   99.35350   82.325933  0.218238        R
Pt37.baseline     7.05431   5.141680   42.87030   18.355430 -0.778974        R
Pt38.baseline    20.19070  15.060300   56.59930   30.616767 -0.587836        R

In [95]:
df_merge.groupby('Response').size()

Response
NR    12
R     15
dtype: int64

In [227]:
col_name= 'z_score'

In [228]:
val_list_3= df_merge[col_name].quantile([.25, .75]).values.tolist()
val_list_3

[-0.4706043535526311, 0.059432399346334014]

In [229]:
def group_3(row, val_list):
    if row[col_name] < val_list[0]:
        return 0
    elif val_list[0] <= row[col_name] < val_list[1]:
        return 1
    elif val_list[1] <= row[col_name]:
        return 2

In [230]:
df_merge['{}_three_clusters'.format(col_name)] = df_merge.apply(lambda row: group_3(row, val_list_3), axis=1)

In [231]:
df_merge

,PHGDH,SFXN1,SLC1A5,mean,z_score,Response,SFXN1_three_clusters,PHGDH_three_clusters,SLC1A5_three_clusters,z_score_three_clusters
Pt1.baseline,178.13350,20.142550,53.88820,84.054750,0.245188,NR,2,2,1,2
Pt2.baseline,12.83100,26.154650,10.17109,16.385580,-0.809681,R,2,0,0,0
Pt4.baseline,125.11000,7.824695,10.61300,47.849232,-0.319206,R,1,2,0,1
Pt5.baseline,161.87850,20.885100,53.91920,78.894267,0.164743,R,2,2,1,2
Pt6.baseline,50.40410,14.311200,10.07938,24.931560,-0.676461,R,1,1,0,0
Pt7.baseline,103.41350,8.216880,831.76650,314.465627,3.836976,NR,1,1,2,2
Pt8.baseline,69.38070,17.229850,69.47360,52.028050,-0.254064,R,1,1,1,1
Pt9.baseline,38.16610,17.720600,61.17790,39.021533,-0.456818,R,2,1,1,1
Pt10.baseline,14.88905,18.938550,77.93055,37.252717,-0.484391,NR,2,0,1,0
Pt12.baseline,51.40225,9.775280,64.15265,41.776727,-0.413868,NR,1,1,1,1
Pt13.baseline,13.29660,9.770205,24.62405,15.896952,-0.817298,R,1,0,0,0
Pt14.baseline,21.93350,17.308900,117.14900,52.130467,-0.252467,NR,2,1,2,1
Pt15.baseline,32.30460,15.100100,95.36450,47.589733,-0.323251,R,1,1,1,1
Pt19.baseline,233.08650,5.727675,431.20100,223.338392,2.416428,R,0,2,2,2
Pt20.baseline,54.03325,7.417420,60.76985,40.740173,-0.430026,NR,0,1,1,1
Pt22.baseline,16.36940,10.583950,37.02740,21.326917,-0.732652,NR,1,0,0,0
Pt23.baseline,63.51005,14.784500,117.85450,65.383017,-0.045878,NR,1,1,2,1
Pt25.baseline,2.06675,7.371015,120.68900,43.375588,-0.388944,NR,0,0,2,1
Pt27A.baseline,293.83700,2.033025,52.61715,116.162392,0.745702,R,0,2,1,2
Pt27B.baseline,301.22950,1.316030,39.34665,113.964060,0.711433,R,0,2,0,2
Pt28.baseline,53.68660,12.351850,84.07135,50.036600,-0.285108,R,1,1,1,1
Pt29.baseline,22.73570,10.051280,97.20070,43.329227,-0.389667,NR,1,1,1,1
Pt31.baseline,22.13350,18.817900,140.05200,60.334467,-0.124578,NR,2,1,2,1
Pt32.baseline,50.75010,7.063920,82.62550,46.813173,-0.335357,NR,0,1,1,1
Pt35.baseline,130.98700,16.637300,99.35350,82.325933,0.218238,R,1,2,2,2
Pt37.baseline,7.05431,5.141680,42.87030,18.355430,-0.778974,R,0,0,0,0
Pt38.baseline,20.19070,15.060300,56.59930,30.616767,-0.587836,R,1,0,1,0

In [232]:
df_temp = df_merge.groupby(['Response','{}_three_clusters'.format(col_name)])[col_name].count().reset_index()
df_temp

  Response  z_score_three_clusters  z_score
0       NR                       0        2
1       NR                       1        8
2       NR                       2        2
3        R                       0        5
4        R                       1        5
5        R                       2        5

In [233]:
temp_numpy = df_temp[col_name].to_numpy()
C = np.reshape(temp_numpy, (-1, 3))
C

array([[2, 8, 2],
       [5, 5, 5]])

In [234]:
df_temp = df_temp[df_temp['{}_three_clusters'.format(col_name)]!=1]
df_temp

  Response  z_score_three_clusters  z_score
0       NR                       0        2
2       NR                       2        2
3        R                       0        5
5        R                       2        5

In [235]:
temp_numpy = df_temp[col_name].to_numpy()
B = np.reshape(temp_numpy, (-1, 2))
B

array([[2, 2],
       [5, 5]])

In [236]:

# importing packages
import scipy.stats as stats
  
#performing fishers exact test on the data
odd_ratio, p_value = stats.fisher_exact(B)
print('odd ratio is : ' + str(odd_ratio))
print('p_value is : ' + str(p_value))

odd ratio is : 1.0
p_value is : 1.0

In [237]:
from scipy.stats import chisquare
from scipy.stats import ttest_ind

In [238]:
chisquare(C, axis=None)

Power_divergenceResult(statistic=5.666666666666666, pvalue=0.34001609192154897)

In [239]:
grp1 = df_merge[df_merge['Response']=="NR"][col_name].to_list()
grp2 = df_merge[df_merge['Response']=="R"][col_name].to_list()

In [240]:
ttest_ind(grp1, grp2)

Ttest_indResult(statistic=0.2766897392524676, pvalue=0.7842931213073902)

In [241]:
col_name

'z_score'