In [2]:
import pandas as pd
import glob

In [5]:
df_acceptor_DBSNP= pd.read_csv("/data/private/pdutta/PSB_Data_2024/Acceptor/combined_file.tsv", sep="\t", header=None)

In [6]:
df_acceptor_DBSNP

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
0,chr10,99729695,99729774,ENST00000016171.6,-,chr10,99710868,99732127,ENST00000016171,-1,chr10,99729695,99729696,rs1276445985,G,1,"A,"
1,chr10,99729695,99729774,ENST00000016171.6,-,chr10,99710868,99732127,ENST00000016171,-1,chr10,99729697,99729698,rs1365182371,A,1,"T,"
2,chr10,99729695,99729774,ENST00000016171.6,-,chr10,99710868,99732127,ENST00000016171,-1,chr10,99729698,99729699,rs773642414,T,1,"C,"
3,chr10,99729695,99729774,ENST00000016171.6,-,chr10,99710868,99732127,ENST00000016171,-1,chr10,99729702,99729703,rs761035049,C,1,"T,"
4,chr10,99729695,99729774,ENST00000016171.6,-,chr10,99710868,99732127,ENST00000016171,-1,chr10,99729703,99729704,rs1554842005,C,1,"A,"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
577264345,chrY,13234787,13234866,ENST00000684326.1,-,chrY,13234599,13336129,ENST00000682761,-1,chrY,13234794,13234795,rs1422913673,G,1,"A,"
577264346,chrY,13234787,13234866,ENST00000684326.1,-,chrY,13234599,13336129,ENST00000682761,-1,chrY,13234797,13234798,rs1162204554,G,1,"A,"
577264347,chrY,13234787,13234866,ENST00000684326.1,-,chrY,13234599,13336129,ENST00000682761,-1,chrY,13234801,13234802,rs1355901236,G,1,"C,"
577264348,chrY,13234787,13234866,ENST00000684326.1,-,chrY,13234599,13336129,ENST00000682761,-1,chrY,13234814,13234815,rs1462345242,C,1,"A,"
577264349,chrY,13234787,13234866,ENST00000684326.1,-,chrY,13234599,13336129,ENST00000682761,-1,chrY,13234851,13234852,rs1603217354,T,1,"A,"

In [8]:
unique_df_acceptor = df_acceptor_DBSNP.drop_duplicates(subset=[0, 1, 2])
unique_df_acceptor

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
0,chr10,99729695,99729774,ENST00000016171.6,-,chr10,99710868,99732127,ENST00000016171,-1,chr10,99729695,99729696,rs1276445985,G,1,"A,"
128,chr10,99727524,99727603,ENST00000016171.6,-,chr10,99710868,99732127,ENST00000016171,-1,chr10,99727529,99727530,rs1051639302,C,1,"A,"
252,chr10,99727115,99727194,ENST00000016171.6,-,chr10,99710868,99732127,ENST00000016171,-1,chr10,99727118,99727119,rs761793891,A,1,"C,"
400,chr10,99724084,99724163,ENST00000016171.6,-,chr10,99710868,99732127,ENST00000016171,-1,chr10,99724087,99724088,rs746153360,T,1,"C,"
484,chr10,99721029,99721108,ENST00000016171.6,-,chr10,99710868,99732127,ENST00000016171,-1,chr10,99721029,99721030,rs2036748069,A,1,"G,"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
577248556,chrY,2789708,2789787,ENST00000680285.1,+,chrY,2752083,2790921,ENST00000680285,1,chrY,2789738,2789739,rs1603308337,C,1,"G,"
577249089,chrY,2787439,2787518,ENST00000680845.1,+,chrY,2786855,2787682,ENST00000383070,-1,chrY,2787448,2787449,rs1325077544,C,1,"T,"
577249600,chrY,2840987,2841066,ENST00000681787.1,+,chrY,2752296,2845689,ENST00000681787,1,chrY,2840990,2840991,rs752629530,G,1,"A,"
577252102,chrY,13334301,13334380,ENST00000682112.1,-,chrY,13248379,13480673,ENST00000331397,-1,chrY,13334311,13334312,rs973137433,A,1,"G,"
577253561,chrY,13234787,13234866,ENST00000682112.1,-,chrY,13234577,13479969,ENST00000682216,-1,chrY,13234788,13234789,rs751401171,G,1,"A,"