In [1]:
import pandas as pd
import glob

In [2]:
df_donor_DBSNP= pd.read_csv("/data/private/pdutta/PSB_Data_2024/Donor/combined_file.tsv", sep="\t", header=None)

In [3]:
df_donor_DBSNP

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
0,chr10,99731920,99731999,ENST00000016171.6,-,chr10,99710868,99732127,ENST00000016171,-1,chr10,99731923,99731924,rs1221216144,C,2,"A,T,"
1,chr10,99731920,99731999,ENST00000016171.6,-,chr10,99710868,99732127,ENST00000016171,-1,chr10,99731924,99731925,rs1233815999,G,1,"A,"
2,chr10,99731920,99731999,ENST00000016171.6,-,chr10,99710868,99732127,ENST00000016171,-1,chr10,99731927,99731928,rs761067193,C,1,"T,"
3,chr10,99731920,99731999,ENST00000016171.6,-,chr10,99710868,99732127,ENST00000016171,-1,chr10,99731928,99731929,rs766895914,C,2,"A,T,"
4,chr10,99731920,99731999,ENST00000016171.6,-,chr10,99710868,99732127,ENST00000016171,-1,chr10,99731929,99731930,rs777261170,C,2,"G,T,"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
576646419,chrY,13245175,13245254,ENST00000684326.1,-,chrY,13234599,13336129,ENST00000682761,-1,chrY,13245187,13245191,rs2053935133,ATAT,1,"AT,"
576646420,chrY,13245175,13245254,ENST00000684326.1,-,chrY,13234599,13336129,ENST00000682761,-1,chrY,13245190,13245191,rs919640556,T,1,"A,"
576646421,chrY,13245175,13245254,ENST00000684326.1,-,chrY,13234599,13336129,ENST00000682761,-1,chrY,13245202,13245203,rs932417894,A,1,"T,"
576646422,chrY,13245175,13245254,ENST00000684326.1,-,chrY,13234599,13336129,ENST00000682761,-1,chrY,13245205,13245206,rs2053935755,T,1,"C,"
576646423,chrY,13245175,13245254,ENST00000684326.1,-,chrY,13234599,13336129,ENST00000682761,-1,chrY,13245206,13245207,rs2053935953,A,1,"G,"

In [4]:
unique_df_donor = df_donor_DBSNP.drop_duplicates(subset=[0, 1, 2])
unique_df_donor

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
0,chr10,99731920,99731999,ENST00000016171.6,-,chr10,99710868,99732127,ENST00000016171,-1,chr10,99731923,99731924,rs1221216144,C,2,"A,T,"
168,chr10,99729513,99729592,ENST00000016171.6,-,chr10,99710868,99732127,ENST00000016171,-1,chr10,99729513,99729514,rs781521324,T,2,"C,G,"
272,chr10,99727401,99727480,ENST00000016171.6,-,chr10,99710868,99732127,ENST00000016171,-1,chr10,99727401,99727402,rs766275086,G,1,"T,"
376,chr10,99726928,99727007,ENST00000016171.6,-,chr10,99710868,99732127,ENST00000016171,-1,chr10,99726924,99726965,rs1337767658,TCCTGGGAGCATTTCTGGTTTCTCAACCTTGAATAAATCTT,1,TCCTGGGAGCATTTCTGGTTTCTCAACCTTGAATAAATCTTTCCTG...
508,chr10,99723916,99723995,ENST00000016171.6,-,chr10,99710868,99732127,ENST00000016171,-1,chr10,99723917,99723918,rs756808368,C,1,"T,"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
576627173,chrY,2774701,2774780,ENST00000679518.1,+,chrY,2752083,2790921,ENST00000680285,1,chrY,2774698,2774705,rs780853837,TCTCTCT,1,"TCTCT,"
576630300,chrY,2787015,2787094,ENST00000680845.1,+,chrY,2786855,2787682,ENST00000383070,-1,chrY,2787018,2787019,rs1381226211,C,1,"G,"
576631084,chrY,2841045,2841124,ENST00000681787.1,+,chrY,2752296,2845689,ENST00000681787,1,chrY,2841055,2841056,rs1473781126,C,1,"T,"
576634098,chrY,13334178,13334257,ENST00000682112.1,-,chrY,13248379,13480673,ENST00000331397,-1,chrY,13334198,13334199,rs774320302,C,1,"T,"
576646394,chrY,13245175,13245254,ENST00000684326.1,-,chrY,13234577,13479969,ENST00000682216,-1,chrY,13245180,13245181,rs1603222665,C,1,"G,"